### ISSUE TITLE
Unmet peer dependency in pnpm with Svelte 4

### ISSUE THREAD

**Issue by matt8707** [bluwy/svelte-fast-dimension#11]
Hi! Everything seems to work fine but npm is throwing this warning with Svelte 4. 
I think ´peerDependencies´ needs to be bumped. Thanks!

```bash
WARN  Issues with peer dependencies found
svelte-fast-dimension 1.0.0
✕ unmet peer svelte@^3.44.1: found 4.0.1
```

**Comment by bluwy** [comment]
Published in v1.1.0!
